---
kind: pipeline
name: Site-Validation

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

environment:
  DOCKER_HOST: tcp://docker-in-docker:2375
  DOCKER_CLI_EXPERIMENTAL: enabled

steps:
  - name: Waiting for Docker to start
    image: cube8021/docker-buildx:20.10.14-0.8.2
    commands:
    - echo 'Waiting for docker to start...'
    - while ! docker info; do sleep 1; done

  - name: Docker Build
    image: cube8021/docker-buildx:20.10.14-0.8.2
    environment:
      DOCKER_USERNAME:
        from_secret: harbor_username
      DOCKER_PASSWORD:
        from_secret: harbor_password
    commands:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD harbor.coxedgecomputing.com
    - export REGISTRY=harbor.coxedgecomputing.com
    - if [ -z "$DRONE_TAG" ]; then export DRONE_TAG=latest; fi
    - export IMAGE_NAME=cluster-api-cox-controller:${DRONE_TAG}
    - make docker-build && make docker-push
    trigger:
      event:
      - tag
      - deployment

services:
- name: docker-in-docker
  docker:
  image: docker:20.10.14-dind
  command: ["dockerd", "--host", "0.0.0.0", "--experimental"]
  privileged: true