apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: capi-coxedge-controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: capi-coxedge-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: capi-coxedge-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: capi-coxedge-controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: controller
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
