apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: coxedge-controller-manager
  name: cluster-api-provider-coxedge-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: coxedge-controller-manager
  name: coxedge-controller-manager
  namespace: cluster-api-provider-coxedge-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: coxedge-controller-manager
  template:
    metadata:
      labels:
        control-plane: coxedge-controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        image: docker.io/coxedge/cluster-api-provider-cox-controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: default
      terminationGracePeriodSeconds: 10
