# permissions for end users to view coxmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coxmachine-viewer-role
rules:
- apiGroups:
  - cluster.capi.pf9.io
  resources:
  - coxmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.capi.pf9.io
  resources:
  - coxmachines/status
  verbs:
  - get
