apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cox-example
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: cluster.capi.pf9.io/v1beta1
    kind: CoxCluster
    name: cox-example
---
apiVersion: cluster.capi.pf9.io/v1beta1
kind: CoxCluster
metadata:
  name: cox-example
  labels:
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/cluster-name: "cox-example"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: cox-example
  labels:
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/cluster-name: "cox-example"
spec:
  version: v1.15.3
  clusterName: cox-example
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: cox-example

  infrastructureRef:
    apiVersion: cluster.capi.pf9.io/v1beta1
    kind: CoxMachine
    name: cox-example

---
apiVersion: cluster.capi.pf9.io/v1beta1
kind: CoxMachine
metadata:
  name: cox-example
  labels:
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/cluster-name: "cox-example"
spec:
  type: VM
  addanycastipaddress: true
  image: stackpath-edge/ubuntu-1804-bionic:v202104291427
  ports:
    - protocol: TCP
      publicPort: "22"
    - protocol: TCP
      publicPort: "80"
    - protocol: TCP
      publicPort: "6443"
  firstBootSshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgnV5MOhBqpQLt66KGlMKi/VYtmVPUt6epSVxnxrvjayNto5flG2sH4cGqdI2C0NE9/w7BFNdwWqp0mL2kYynC8l+SejW/qjx37hrEBWIXqdTyumchm0LD/7K7P7/kz14IV5NcHjNAsntPgKjx/fzJlbA1VCQYmnOq9RZeKme44rdHYW0BBfgMzekcEbyGTNDGp51NYhVafZLXsF8MzCKlJ+NCPlDqzD6w0fQe/qtMFO8NbFyS9/Lk4prp4HAWEyLSM26w1iLycYpbpWrHw6oc1U7bNIgbsa0ezDu4+OPkxeHz7aG5TeJ/dn0Wftzdfy2sy5PJy5MnYP3RTuROsOv+chu+AshZNNJ9A4ar5gFXSX40sQ0i4GzxZGrsKhW42ZP4sElzV74gEBQ2BOIOJUh4qGRtnjsQCJHBs7DLgpeVeGUq2B7p5zDAlJBGCXiHuTgIM8aVnpdnNrFwmr9SF66iaTrt7x8HinNOCIIztMU15Fk2AYSxSEuju1d3VcPt/d0= jasmingacic@Jasmins-MBP
  deployments:
    - name: cox-example-deployment
      pops:
        - LAX
      instancesPerPop: "1"
  specs: SP-5
  userData: |-
    runcmd:
    - curl -sfL https://get.k3s.io | sh -
    - [ cloud-init-per, once, mymkfs, mkfs, /dev/vdb ]