apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: pmk-cox-1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.20.0.0/22
    services:
      cidrBlocks:
        - 10.21.0.0/22
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: NodeletControlPlane
    name: pmk-cox-1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: CoxCluster
    name: pmk-cox-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: CoxCluster
metadata:
  name: pmk-cox-1
  namespace: default
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: NodeletControlPlane
metadata:
  name: pmk-cox-1-control-plane
  namespace: default
spec:
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: CoxMachineTemplate
      name: pmk-cox-1-control-plane
    nodeletConfigSpec: {}
  replicas: 1
  version: v1.20.11
  cni:
    calico:
      natOutgoing: true
      IPIPMode: "Always"
  schedulable: true
  apiserver:
    privileged: true # Needed for calico
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: CoxMachineTemplate
metadata:
  name: pmk-cox-1-control-plane
  namespace: default
spec:
  template:
    spec:
      image: stackpath-edge/ubuntu-2004-focal:v202102241556
      ports:
        - protocol: TCP
          publicPort: "22"
        - protocol: TCP
          publicPort: "6443"
      sshAuthorizedKeys:
        - $SSH_KEY
      deployments:
        - name: default
          pops:
            - LAS
          instancesPerPop: "1"
      specs: SP-5
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: pmk-cox-1-md-0
  namespace: default
spec:
  clusterName: pmk-cox-1
  replicas: 1
  selector:
    matchLabels:
      machineDeployment: pmk-cox-1-md-0
  template:
    metadata:
      labels:
        machineDeployment: pmk-cox-1-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: NodeletConfigTemplate
          name: pmk-cox-1-md-0
      clusterName: aws-quickstart
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: CoxMachineTemplate
        name: pmk-cox-1-md-0
      version: v1.20.11
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: CoxMachineTemplate
metadata:
  name: pmk-cox-1-md-0
  namespace: default
spec:
  template:
    spec:
      image: stackpath-edge/ubuntu-2004-focal:v202102241556
      ports:
        - protocol: TCP
          publicPort: "22"
        - protocol: TCP
          publicPort: "6443"
      sshAuthorizedKeys:
        - $SSH_KEY
      deployments:
        - name: default
          pops:
            - LAS
          instancesPerPop: "1"
      specs: SP-5
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: NodeletConfigTemplate
metadata:
  name: pmk-cox-1-md-0
  namespace: default
spec:
  template:
    spec: {}