name: golangci-lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
    # Needed to give workflow access to private PF9 repositories
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      GOPRIVATE: github.com/coxedge
    strategy:
      matrix:
        working-directory:
          - ./
    steps:
      - name: Configure go private repo access
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
          args: --timeout=5m
          working-directory: ${{matrix.working-directory}}